version: '2'
services:
  tema3_spring-app:
    image: tema3_spring
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://tema3_spring-mysql:3306/tema3_spring?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  tema3_spring-mysql:
    extends:
      file: mysql.yml
      service: tema3_spring-mysql
